spring:
  application:
    name: foody

  # 데이터베이스 연결 설정 (p6spy 적용)
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/foody?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: your_username
    password: your_password

  # JPA 및 Hibernate 설정 수정
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        spatial:
          enabled: true
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: false  # p6spy가 포맷팅하므로 false로 변경
        use_sql_comments: false  # p6spy가 처리하므로 false로 변경
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false  # p6spy가 SQL을 출력하므로 false로 변경

# 로깅 설정 수정
logging:
  level:
    com.umc.foody: INFO
    org.springframework.security: INFO
    p6spy: INFO  # p6spy 로그 레벨 추가
    # 기존 Hibernate 로그는 제거하거나 DEBUG로 변경
    # org.hibernate.SQL: DEBUG
    # org.hibernate.type.descriptor.sql.BasicBinder: DEBUG

# Swagger 설정 (기존 유지)
springdoc:
  version: '1.0.0'
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  paths-to-match:
    - /api/**