version: '3'

services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql-local
    restart: always
    ports:
      - '3307:3306'
    env_file:
      - ../.env
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: 'Asia/Seoul'
    volumes:
      - foody-local-database:/var/lib/mysql


  redis:
    image: redis:7.2.4-alpine
    container_name: redis-local
    command: redis-server --port ${REDIS_PORT}
    restart: always
    hostname: root
    labels:
      - 'mode:standalone'
    ports:
      - '6379:6379'

volumes:
  foody-local-database:
