version: '3'

services:
  redis:
    image: redis:7.2.4-alpine
    container_name: redis-local
    command: redis-server --port ${REDIS_PORT}
    restart: always
    hostname: root
    labels:
      - 'mode:standalone'
    ports:
      - '6379:6379'
