name: PR CI Test

on:
  pull_request:
    branches: ["develop"]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Set up Redis container
        run: |
          docker-compose -f ./docker/redis-compose.yml up -d
          echo "Waiting for Redis to be ready.."
          for i in {1..30}; do
            docker ps | grep redis-local && echo "✅ Redis ready." && break
            echo "⏳ Waiting for Redis... ($i)"
            sleep 2
          done

      - name: Create .env file for RDS and Redis
        run: |
          echo "DB_HOST=${{ secrets.RDS_ENDPOINT }}" >> .env
          echo "DB_PORT=${{ secrets.RDS_PORT }}" >> .env
          echo "DB_DATABASE=${{ secrets.RDS_DATABASE }}" >> .env
          echo "DB_USERNAME=${{ secrets.RDS_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.RDS_PASSWORD }}" >> .env
          echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> .env

      - name: Run tests
        run: ./gradlew test

      - name: Publish test results to PR
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: '**/build/test-results/test/**/*.xml'

      - name: Clean up Redis container
        if: always()
        run: docker-compose -f ./docker/redis-compose.yml down
